import localFont from "next/font/local";
import Menubar from "@/components/NavBar/menubar";
import Footer from "@/components/Footer/Footer";
//import tailwind css
import "../app/globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title:{template:'%s | Next JS',
    default: 'Next Js'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Menubar/>
        {children}

<Footer/>
      </body>
    </html>
  );
}
